### ISSUE TITLE
Week 1 Lab 

### ISSUE THREAD

**Issue by TM11153431** [Vluuks/AndroidPractice#23]
Hee hoi ik had nog wat opmerkingen over week 1 lab (die er verder wel echt heel goed uitzag hoor, een mooie lab)

Okay het is eigenlijk alleen maar taaldingen denk ik, feel free om het er niet mee eens te zijn :)

Je zegt ergens "an built in editor", dit moet "a built-in editor" zijn

"In Java, in order to use classes like the Student class, they need to be instantiated before they can be used." ik denk dat hier "before they can be used" wel weg kan, want je zegt al "in order to use classes"

"The Student class can be seen as a blueprint. It exists, but before we can use the properties or methods inside, we first need to create an instance of the class. An instance of a class is often called an object as well. A class is a blueprint which you use to create objects. These objects are instances of that particular class." best wel veel dubbelop hier

"This instance will contain actual information about a particular student, which the class blueprint does not." ik denk dat je hier while bedoelt i.p.v. which, al kan het ook met which hoor

Groeten,

Tim

**Comment by Vluuks** [comment]
♥
